language: node_js
node_js:
  - "0.10"
script: gulp
after_success: ./deploy.sh

env:
  global:
    REPO_REF: github.com/AlvTech/AlvTech.github.io.git
    secure_token: aLZ3iCf+CFyVhSL9E1sEDvBQSeXjzsi28uBqzG+/HgDuiqZx3BS+xAXAosFPUOxh6O7R1K1WXnPSnJEni6Z8k3NKhMNMv6hiS7Vlx0wQyGrgYB+3O4ZiHjrVjdcm0PjlQY9ifFSxWrqDXHvek3EyV1e62XkiI5KUdsUCRukWkg4=
